# Data paths
data_path: "data/"

# Stock symbols
target_symbol: "MSFT"
peer_symbols:
  - "AAPL"
  - "AMZN"
  - "GOOGL"
  - "MSFT"
  - "META"
  - "ORCL"
  - "IBM"
  - "CRM"
  - "ADBE"
  - "NVDA"
  - "INTC"
  - "SPY"
  - "QQQ"
  - "XLK"
  - "VTI"


# Model parameters
prediction_horizon: 5  # days

# Feature parameters
features:
  technical:
    rsi:
      enabled: true
      period: 21
    macd:
      enabled: true
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger:
      enabled: true
      window: 15
      std: 1.5
    cci:
      enabled: true
      period: 20
    stochastic:
      enabled: true
      k_period: 14
      d_period: 3
    atr:
      enabled: true
      period: 14
    obv:
      enabled: true
      window: 20
    ichimoku:
      enabled: true
      conversion_period: 9
      base_period: 26
    sma:
      enabled: true
      periods: [5, 10, 20, 50]
  
  # Lagged price features
  lags:
    enabled: true
    price_columns: ["Close", "High", "Low", "Open", "Volume"]
    lag_periods: [1, 2, 3, 5, 10, 20]  # Trading days
    include_target: true   # Include target symbol lagged features
    include_peers: true    # Include peer symbols lagged features
    rolling_features:      # Additional rolling window features
      enabled: true
      windows: [5, 10, 20]
      functions: ["mean", "std", "min", "max"]

# API configuration
yahoo_finance:
  batch_size: 100
  rate_limit: 2000  # requests per hour

# Backtesting parameters
backtesting:
    initial_capital: 5000
    entry_threshold: 295.0  # Set to realistic price level
    exit_threshold: 305.0   # Set to realistic price level
    position_size: 0.1  # 10% of capital per trade
    max_positions: 5
    stop_loss: 0.02    # 2% stop loss
    take_profit: 0.05  # 5% take profit
    max_trades: 10     # Maximum number of trades allowed

# Training and strategy periods
periods:
  training:
    start: '2020-01-01'
    end: '2023-12-31'
  test:
    start: '2024-01-01'
    end: '2024-12-31' 
  strategy:
    start: '2025-01-01'
    end: '2025-06-01'

# Alpaca API configuration
alpaca:
  api_key: "PKZ9T5ZGPQSFJJSB0J4N"
  secret_key: "zEyCkauW58QOnloTgQHj5kBNQg78SJfbGUDm4fYg"
  base_url: "https://paper-api.alpaca.markets/v2"  # Paper trading
  # base_url: "https://api.alpaca.markets"  # Live trading (use with caution)

